### PR TITLE
add ModifyVars to parser

### PR DESCRIPTION
**Pull request by BernhardBaumrock**
Hey Ryan,
this update makes it possible to set custom LESS variables via PHP (not only in LESS files). This makes it possible to set colors for the admin theme from inputfields or the like.

### CODE REVIEW

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Sounds good for the vars option. For the parse option, isn't this already covered by the parse() method in this module? Or is it just an alias to have it as an option?

**Comment by BernhardBaumrock** [comment]
Hey @ryancramerdesign thx :) I don't think so. My PR makes it possible to set the parse string via the config setting, see https://github.com/processwire/processwire/pull/207

We could use `$this->parse($parse)` instead of my `$this->parser()->parse($parse);` but having only the `parse()` method (not the config setting) would not be the same I think.

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Okay sounds good. If we have that, it makes me wonder if I should also add a `parseFiles` option to accompany the `parse` option on the saveCss method?

**Comment by BernhardBaumrock** [comment]
@ryancramerdesign I think this is what the `customLessFiles` option does?

This is how the new options work in action: https://processwire.com/talk/topic/25668-adminstylerock-module-and-docs-for-adminthemeuikit-rock-style/#comment-220420 :)

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock My question is actually just specific to the Less module, independent of any particular usage. I was thinking that if there's a `parse` option to the `saveCss` method that duplicates the existing `parse()` method then maybe there should also be a `parseFiles` option that is an alternative to the existing `parseFile()` method (just as a matter of consistency in the Less module).

**Comment by BernhardBaumrock** [comment]
Now I get what you are saying - I mixed up the two PRs. Wait a second... I think it would be better to refactor this PR! I'll report back...

**Comment by BernhardBaumrock** [comment]
Hey Ryan,

I had another look... actually what I wanted to do is setting a single variable via PHP. That should happen in AdminThemeUikitCss.php and not in the Less module. What I tried first was this:

image

But that does not work. I don't know why. If that worked we would not need to change anything in the existing Less module. Do you know why it does not work the way I tried it?

**Comment by BernhardBaumrock** [comment]
I found the issue and I will prepare a new PR!

**Comment by BernhardBaumrock** [comment]
sorry for the confusion! here we go: https://github.com/processwire/processwire/pull/208

**Pull request closed without merging**
